### ISSUE TITLE
Saving to EEPROM not working

### ISSUE THREAD

**Issue by hynci117** [USIWP1Module/USI_I-NUCLEO-LRWAN1#11]
The problem:  when the module is in idle mode, saving address with the WDCT command will not work. Firmware version 3.7
Command sequence example:
> ATZ
> \# đ                                                                  
> AT+VERB=1
> \# OK                                                                    
> AT+DEFMODE=0
> \# OK                                                                 
> AT+ADDR=11223344
> OK                                                              
> \# 
> AT+WDCT                                                              
> \# OK
> ATZ
> \# đ                                                                
> AT+ADDR
> \# +ADDR=00,00,00,00
> OK                                                              
> \# 

As you can see, after reset the address is set to zeroes. Also reading EUI gives a different value than before.
When I reset the settings with AT+WDCT=0 and repeat the same sequence **without** going to idle mode, everything works as expected and the address is kept in eeprom. Previously I suspected the verbose command, but it seems to be related to the Idle mode command (use it to configure RF settings in a production test).
Is there a workaround to use idle mode and the ability to persist settings in eeprom?

**Comment by USI-ShellyWu** [comment]
Please try below after modified address:
AT+ADDR= 11223344
AT+WDCT
AT+ADDR //the address is 11 22 33 44
AT+DEFMODE=6
ATZ // reset shield board
AT+DEFMODE // sure that mode is lora wan mode
AT+ADDR  // the address should be 11 22 33 44

**Comment by USI-ShellyWu** [comment]
the address is valid in lora wan mode, not for other modes.
