### ISSUE TITLE
Add DFU image for version 3.7 firmware

### ISSUE THREAD

**Issue by hynci117** [USIWP1Module/USI_I-NUCLEO-LRWAN1#27]
The DFU firmware image is currently available only for the 4.0.1 version.
Is it possible to add DFU images for older versions of firmware as well? 
Please upload the img files for version 3.7. We need to perform a downgrade due to issues with the new versions.

**Comment by slc0508** [comment]
Due we modified the FW structure between V3.x to V4.x ; that can't practice V3.x with DFU mode ; the only way is to perform older FW updated method to downgrade FW from V4.x to V3.x as you learned

**Comment by hynci117** [comment]
Unfortunate, but I understand the reasons
