### ISSUE TITLE
sm42_backup doesn't create a backup

### ISSUE THREAD

**Issue by OlegSomov** [USIWP1Module/USI_I-NUCLEO-LRWAN1#3]
Boar connected to the laptop using UART interface.
The result after running sm42_backup.bat 62 is (62 is the COM port number):
![image](https://user-images.githubusercontent.com/19969581/37057663-18d40b6a-2156-11e8-8528-38531473f570.png)
After that program exits. Tried to connect using SWD connecting and STLink2 but device not even shows up in the Device Manager..

Any ideas?

**Comment by OlegSomov** [comment]
Changed COM port number to 28  (so it's between 1 and 60). Same result

**Comment by USI-ShellyWu** [comment]
1. Please make sure the comport is configured to be from 1 to 50.
2. Please make sure to run "sm42_backup.bat [comport no.]" as administration, like D:\sm42_fw_update_tool_v1.1\sm42_fw_update_tool_v1.1\bin\sm42_backup.bat 20.

**Comment by USI-ShellyWu** [comment]
We have updated WM-SG-SM-42 Update Preloaded AT Command FW Application Note rev. 1.4.pdf for ST-lin/V2 to backup or upgrade. Please follow the latest commands.
