### ISSUE TITLE
I-NUCLEO-LRWAN1 I can't connect with Tera Term/ Doesn't send uplinks

### ISSUE THREAD

**Issue by MilorES** [USIWP1Module/USI_I-NUCLEO-LRWAN1#33]
I am using a translator so I apologize in advance my native language is Spanish.

Connect the mini usb, I open the program and cannot send any AT command or write :(

It natively has temperature, humidity, barometer...

![Image of console ttn](https://i.ibb.co/MPTKKdB/datosaplicacion.png)
![Image of update](https://i.ibb.co/7bvMnhs/upgrade.png)

Do I need to charge you something? I am doing something wrong?

**Comment by slc0508** [comment]
you need issue the AT CMD via the hyper-terminal COM port via the mini-USB(checked it from your device manager)
